language: clojure

addons:
  postgresql: "9.4.1"

before_script:
  - psql -c 'create database toshtogo;' -U postgres

services:
  - postgresql

install: lein sub deps

script:
  - lein sub midje
  - lein sub uberjar
